// <auto-generated />
namespace WetherApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tempcons : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tempcons));
        
        string IMigrationMetadata.Id
        {
            get { return "201906291740141_temp-cons"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
